# Generated by Django 2.0.7 on 2019-01-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fsm_log', '0003_statelog_description_squashed_0005_description_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statelog',
            name='object_id',
            field=models.CharField(db_index=True, max_length=36),
        ),
    ]
